CREATE DATABASE WEB25;
USE WEB25;

CREATE TABLE USUARIO (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255), dOB VARCHAR(10), email VARCHAR(255), senha VARCHAR(255), role VARCHAR(20) DEFAULT 'user');
SELECT * FROM USUARIO;


CREATE TABLE FILME (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255), ano VARCHAR(10), capa VARCHAR(255));
SELECT * FROM FILME;

CREATE TABLE CATEGORIA (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255) NOT NULL;
SELECT * FROM CATEGORIA;
INSERT INTO categoria (id, nome) VALUES (1, 'Ação'), (2, 'Comédia'), (3, 'Drama');

DESCRIBE FILME;
ALTER TABLE filme ADD COLUMN categoria_id INT;
ALTER TABLE filme ADD CONSTRAINT fk_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON DELETE SET NULL;


DROP TABLE USUARIO;
DROP TABLE FILME;
DROP TABLE CATEGORIA;
ALTER TABLE FILME DROP FOREIGN KEY fk_categoria;

UPDATE USUARIO SET role = 'admin' WHERE id = 2;