CREATE DATABASE WEB25;
USE WEB25;

DROP TABLE USUARIO;
CREATE TABLE USUARIO (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255), dOB DATE, email VARCHAR(255), img VARCHAR(255));
SELECT * FROM USUARIO;

DROP TABLE FILME;
CREATE TABLE FILME (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255), ano DATE, genero VARCHAR(25), capa VARCHAR(255));
SELECT * FROM FILME;
DESCRIBE FILME;
ALTER TABLE filme MODIFY capa VARCHAR(255);